stages:
  - build
  - test


variables:
  WORKDIR: "_work/client"
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "-f $WORKDIR -s $WORKDIR/ci_settings.xml -U --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  DS_DISABLE_DIND: "true"


# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository


compile:jdk8:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - 'mvn $MAVEN_CLI_OPTS -DskipTests compile'


test:
  stage: test
  image: maven:3.3.9-jdk-8
  script:
  - 'mvn $MAVEN_CLI_OPTS test'
  - 'mvn $MAVEN_CLI_OPTS jacoco:report'
  - 'cat _work/client/target/site/jacoco/index.html | grep -o "<tfoot>.*</tfoot>"'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
    - _work/client/target/surefire-reports/*
    - _work/client/target/site/jacoco/*
    reports:
      junit:
      - _work/client/target/surefire-reports/TEST-*.xml



include:
  template: Dependency-Scanning.gitlab-ci.yml
# --> https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/Dependency-Scanning.gitlab-ci.yml

dependency_scanning:
  variables:
    MAVEN_CLI_OPTS: "-s ci_settings.xml -U --batch-mode --errors --fail-at-end --show-version -DskipTests"
    DS_DEFAULT_ANALYZERS: "gemnasium-maven"
